updated micronaut version
micronaut-guides/micronaut-creating-first-graal-app pull request #25
Opened 2021-03-11 17:30 UTC by jeevanjoseph

Fixes #24 - where the `complete` version of the app is not buildable.

2021-03-12 09:03 UTC, ilopmar requested changes
Can you please try with 2.4.0 and do the change?

2021-03-12 19:22 UTC, jeevanjoseph commented
> Can you please try with 2.4.0 and do the change?

Yes - No issues with 2.4.0 as well. 

```
─ ./gradlew clean build

> Task :complete:compileJava
Note: Creating bean classes for 2 type elements

> Task :complete:compileTestJava
Note: Creating bean classes for 1 type elements
Note: /Users/jgjoseph/dev/micronaut-creating-first-graal-app/complete/src/test/java/example/micronaut/ConferenceControllerTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jgjoseph/dev/micronaut-creating-first-graal-app/complete/src/test/java/example/micronaut/ConferenceControllerTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 17s
15 actionable tasks: 15 executed
```

2021-03-15 07:50 UTC, ilopmar approved these changes

2021-03-15 07:51 UTC, merged

2021-03-15 07:51 UTC, ilopmar commented
Thanks!